### ISSUE TITLE
Linux&Windows?

### ISSUE THREAD

**Issue by Jetlum** [decosoftware/deco-ide#109]
Come on guys make it available for Linux and Windows too

**Comment by dabbott** [comment]
We're gonna publish a roadmap soon so you can get a better idea of what to expect from the Deco core team (me, Gavin, David).

Probably if you want to see Deco for Linux or Windows the fastest way is still to contribute. Now that we have Android support, I think these efforts make more sense.

**Comment by dabbott** [comment]
Closing. See #10 #14
