### ISSUE TITLE
React Native is Cross Platform. Plans for adding Android to Simulator?

### ISSUE THREAD

**Issue by framerate** [decosoftware/deco-ide#12]
Super excited to get the download today! But then bummed that my RN android app apparently isn't supported.

Any plans for this?

**Comment by ivanistheone** [comment]
The GUI seems to be hooked to the iOS simulator by default, but I imagine they'll make that configurable.

I tried calling `react-native run-android` from the command line, but I got:

    Task 'installDebug' not found in root project 'Project'.

which tells me the gradle configs need more love, but I'm sure it will build too...

**Comment by gdowens** [comment]
Yes, we've wanted Android support for awhile but have focused on smoothing out the iOS experience first. Definitely something to add to our roadmap.

**Comment by ianjohnspain** [comment]
I would suggest implementing some kind of config file / plugin. So that you are able to preconfigure simulators / emulators etc. Just an idea.

**Comment by revisionfour** [comment]
Definitely need to add Android support. I was excited about this until I saw that it was pretty much strictly tailored to iOS development. Back to doing Android React Native dev with Sublime.

**Comment by ACCTFORGH** [comment]
Was really excited about the work. Look forward to the Android support!

**Comment by alterx** [comment]
Maybe someone from the core team could provide a high level description of what needs to be achieved in order to make this work, that way it's easier for one of us to contribute @gdowens @dabbott

**Comment by gdowens** [comment]
In progress... should open something next week geared around broadening support and making builds easily customizable. Stay tuned.


<img width="1457" alt="androidondeco" src="https://cloud.githubusercontent.com/assets/977466/15623680/0050c354-242c-11e6-999d-15d3fe9e8816.png">

**Comment by gdowens** [comment]
Added in this 0.7.0 release.
