### ISSUE TITLE
Clicking files doesn't open a new tab

### ISSUE THREAD

**Issue by zombeej** [decosoftware/deco-ide#126]
When clicking a file in the left column file browser, the file replaces the first (and only) tab in the editor. It is not possible to have more than one file open at a time.

```
  Deco Version 1.1.2 (0.7.1)
  OS X v10.11.5
  Model Identifier:	MacBookPro10,1
  Processor Name:	Intel Core i7
  Processor Speed:	2.3 GHz
  RAM:				16GB
```

**Comment by johnryan** [comment]
@zombeej I believe this is the intended behavior (it works the same in the atom text editor). You must double click on a file for it to stay open, one click just "previews" the file.

**Comment by zombeej** [comment]
Ah, you're right. My apologies.
