### ISSUE TITLE
Deco won't install on Mac OSX 

### ISSUE THREAD

**Issue by mujuni88** [decosoftware/deco-ide#132]
Installation failed.

System: MacBook Pro (13-inch, Early 2011)
Version: OS X El Capitan Version 10.11.6

**Comment by gdowens** [comment]
Can you try installing again, then open Console app and look at system.log to see if you can find an error related to "decosoftware".

**Comment by mujuni88** [comment]
Aug  4 14:24:14 JoeBuzaMac CoreServicesUIAgent[16303]: Error -60005 creating authorization
Aug  4 14:24:20 JoeBuzaMac SecurityAgent[23351]: activateIgnoringOtherApps:1
Aug  4 14:24:20 JoeBuzaMac SecurityAgent[23351]: makeKeyAndOrderFront
Aug  4 14:24:20 JoeBuzaMac SecurityAgent[23351]: com.apple.SecurityAgent.consoleLogin.UIShown
Aug  4 14:24:27 JoeBuzaMac UserEventAgent[53]: Failed to send message because the port couldn't be created.
Aug  4 14:24:28 JoeBuzaMac lsd[292]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
Aug  4 14:24:31 JoeBuzaMac kernel[0]: fsevents: watcher falling behind: bzserv (pid: 55) rd:  590 wr:  590 q_size: 1024 flags: 0x1
Aug  4 14:24:31 JoeBuzaMac kernel[0]: fsevents: watcher falling behind: bzserv (pid: 55) rd:  335 wr:  335 q_size: 1024 flags: 0x1
Aug  4 14:24:31 JoeBuzaMac kernel[0]: fsevents: watcher falling behind: bzserv (pid: 55) rd:   80 wr:   80 q_size: 1024 flags: 0x1
Aug  4 14:24:31 JoeBuzaMac kernel[0]: fsevents: watcher falling behind: bzserv (pid: 55) rd:  395 wr:  395 q_size: 1024 flags: 0x1
Aug  4 14:24:31 JoeBuzaMac kernel[0]: fsevents: watcher falling behind: bzserv (pid: 55) rd:  140 wr:  140 q_size: 1024 flags: 0x1
Aug  4 14:24:31 JoeBuzaMac kernel[0]: fsevents: watcher falling behind: bzserv (pid: 55) rd:  909 wr:  909 q_size: 1024 flags: 0x1
Aug  4 14:24:31 JoeBuzaMac kernel[0]: fsevents: watcher falling behind: bzserv (pid: 55) rd:  654 wr:  654 q_size: 1024 flags: 0x1
Aug  4 14:24:31 JoeBuzaMac kernel[0]: fsevents: watcher falling behind: bzserv (pid: 55) rd:  399 wr:  399 q_size: 1024 flags: 0x1
Aug  4 14:24:31 JoeBuzaMac kernel[0]: fsevents: watcher falling behind: bzserv (pid: 55) rd:  144 wr:  144 q_size: 1024 flags: 0x1
Aug  4 14:24:31 JoeBuzaMac kernel[0]: fsevents: watcher falling behind: bzserv (pid: 55) rd:  913 wr:  913 q_size: 1024 flags: 0x1
Aug  4 14:24:31 JoeBuzaMac kernel[0]: fsevents: watcher falling behind: bzserv (pid: 55) rd:  658 wr:  658 q_size: 1024 flags: 0x1
Aug  4 14:24:31 JoeBuzaMac kernel[0]: fsevents: watcher falling behind: bzserv (pid: 55) rd:  403 wr:  403 q_size: 1024 flags: 0x1
Aug  4 14:24:31 JoeBuzaMac kernel[0]: fsevents: watcher falling behind: bzserv (pid: 55) rd:  148 wr:  148 q_size: 1024 flags: 0x1
Aug  4 14:24:31 JoeBuzaMac kernel[0]: fsevents: watcher falling behind: bzserv (pid: 55) rd:  917 wr:  917 q_size: 1024 flags: 0x1
Aug  4 14:24:32 JoeBuzaMac kernel[0]: fsevents: watcher falling behind: bzserv (pid: 55) rd:  662 wr:  662 q_size: 1024 flags: 0x1
Aug  4 14:24:32 JoeBuzaMac sudo[23364]:     root : user NOT in sudoers ; TTY=unknown ; PWD=/private/tmp/PKInstallSandbox.94Ffs9/Scripts/com.decosoftware.deco.TvawoY ; USER=root ; COMMAND=/usr/sbin/chown -R joebm08:staff /Users/joebm08/Library/Application Support/com.decosoftware.Deco
Aug  4 14:24:33 JoeBuzaMac UserEventAgent[53]: Failed to send message because the port couldn't be created.
Aug  4 14:24:33 JoeBuzaMac Installer[23350]: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Aug  4 14:24:39 JoeBuzaMac lsd[210]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
Aug  4 14:24:39 JoeBuzaMac lsd[292]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
Aug  4 14:24:45 --- last message repeated 1 time ---
Aug  4 14:24:45 JoeBuzaMac mdworker[23369]: code validation failed in the process of getting signing information: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)" UserInfo={SecCSArchitecture=i386}
Aug  4 14:24:47 JoeBuzaMac mdworker[23370]: code validation failed in the process of getting signing information: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)" UserInfo={SecCSArchitecture=i386}

**Comment by gdowens** [comment]
Ok, so this is the problem line: Aug 4 14:24:32 JoeBuzaMac sudo[23364]: root : user NOT in sudoers ; TTY=unknown ; PWD=/private/tmp/PKInstallSandbox.94Ffs9/Scripts/com.decosoftware.deco.TvawoY ; USER=root ; COMMAND=/usr/sbin/chown -R joebm08:staff /Users/joebm08/Library/Application Support/com.decosoftware.Deco

your user account joebm08 does not have sudo access.

**Comment by mujuni88** [comment]
I do tho. I checked the sudoers file.

**Comment by gdowens** [comment]
@mujuni88 appreciate your help looking into this... Are you somehow installing the application as ROOT? However, in this case, the postinstall script is supposed to exit immediately. So I suspect you would get a different error message.

These problems can be a challenge to debug as they are not easy to reproduce locally.

FYI: This is the file that is failing for you. https://github.com/decosoftware/deco-ide/blob/master/desktop/Scripts/postinstall

**Comment by mujuni88** [comment]
I was able to install it after I added root into the sudoers file. Which makes sense if you look into this line
