### ISSUE TITLE
`Error: spawn xcodebuild ENOENT` when attempting to build

### ISSUE THREAD

**Issue by jameswomack** [decosoftware/deco-ide#148]
Hey there! I'm getting `Error: spawn xcodebuild ENOENT` when trying to build my app for the first time. I made sure `xcodebuild` is installed and in my path. I'm able to manually run the command so I'm unsure why Deco cannot find it.

```
package.json
×
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn xcodebuild ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:141:18)
    at node.js:933:3
```

Any clues on how to move past this?

**Comment by dchen** [comment]
@jameswomack Did you happen to resolve this issue already?

If not, can you please run these three commands in Terminal and let me know what you get:
```
which xcodebuild
ls -al `which xcodebuild`
xcodebuild -version
```

**Comment by MeganGilligan1** [comment]
Had this problem today, was a simple fix by changing which file directory it was coming from, i.e. it couldn't find the ios build. Need to make sure you open the root folder.

**Comment by iamraafay** [comment]
I'm opening the root of a project here, but I still this issue.

**Comment by Asinox** [comment]
I'm facing the same problem.

@dchen for me the three commands:
```
/usr/bin/xcodebuild
-rwxr-xr-x  1 root  wheel  18304 Dec  1 15:39 /usr/bin/xcodebuild
Xcode 9.2
Build version 9C40b
```

**Comment by jameswomack** [comment]
@dchen I'm no longer experiencing this issue

**Comment by jmargolisvt** [comment]
What was the fix that worked for you, @jameswomack ?

**Comment by jacob-cross99** [comment]
Yeah, I'm having the same issue... I can run xcodebuild from the terminal so not really sure.. Maybe  a permission issue? I don't know if it's the same issue but also run packager failed with 'cannot read property run of undefined' (cli is undefined).

**Comment by jacob-cross99** [comment]
@dchen

**Comment by iba-1** [comment]
I'm having the same problem as well, @jameswomack can you tell us what was the fix?
