### ISSUE TITLE
Bug while opening existing project.

### ISSUE THREAD

**Issue by Gagege** [decosoftware/deco-ide#17]
When I start a new project everything works fine, but if I open an existing project the Project explorer is blank and I can't open any files.

**Comment by gdowens** [comment]
@Gagege can you take a look at `~/Library/Application Support/com.decosoftware.Deco/logs.out` and see if there's some hint about what's going on?

**Comment by Gagege** [comment]
I don't see anything unusual.

Just this line:
`{"level":"info","message":"Deco initializing...","timestamp":"2016-05-26T03:57:16.877Z"}`

**Comment by lggdance** [comment]
Same problem here.

**Comment by lggdance** [comment]
"level":"info","message":"Looking for JS files in\n   /Users/xxx/Documents/xxx/App Development/React Native/xxx \n\n","timestamp":"2016-06-11T00:08:50.704Z"}
{"level":"info","message":"[2:08:54 AM] <START> Building Dependency Graph\n","timestamp":"2016-06-11T00:08:55.003Z"}
{"level":"info","message":"[2:08:55 AM] <START> Crawling File System\n","timestamp":"2016-06-11T00:08:55.004Z"}
{"level":"info","message":"[Hot Module Replacement] Server listening on /hot\n","timestamp":"2016-06-11T00:08:55.871Z"}
{"level":"info","message":"\nReact packager ready.\n\n","timestamp":"2016-06-11T00:08:55.876Z"}
{"level":"info","message":"[2:08:56 AM] <END>   Crawling File System (1312ms)\n","timestamp":"2016-06-11T00:08:56.322Z"}
{"level":"info","message":"[2:08:56 AM] <START> Building in-memory fs for JavaScript\n","timestamp":"2016-06-11T00:08:56.345Z"}
{"level":"info","message":"[2:08:56 AM] <END>   Building in-memory fs for JavaScript (587ms)\n","timestamp":"2016-06-11T00:08:56.934Z"}
{"level":"info","message":"[2:08:56 AM] <START> Building in-memory fs for Assets\n","timestamp":"2016-06-11T00:08:56.937Z"}
{"level":"info","message":"[2:08:57 AM] <END>   Building in-memory fs for Assets (334ms)\n","timestamp":"2016-06-11T00:08:57.271Z"}
{"level":"info","message":"[2:08:57 AM] <START> Building Haste Map\n","timestamp":"2016-06-11T00:08:57.273Z"}
{"level":"info","message":"[2:08:57 AM] <START> Building (deprecated) Asset Map\n","timestamp":"2016-06-11T00:08:57.753Z"}
{"level":"info","message":"[2:08:57 AM] <END>   Building (deprecated) Asset Map (101ms)\n","timestamp":"2016-06-11T00:08:57.854Z"}
{"level":"info","message":"[2:08:58 AM] <END>   Building Haste Map (1363ms)\n","timestamp":"2016-06-11T00:08:58.638Z"}
{"level":"info","message":"[2:08:58 AM] <END>   Building Dependency Graph (3643ms)\n","timestamp":"2016-06-11T00:08:58.638Z"}
{"level":"error","message":"packager stderr [sane] Warning: Lost connection to watchman, reconnecting..\n","timestamp":"2016-06-11T00:09:37.464Z"}
{"level":"info","message":"Deco initializing...","timestamp":"2016-06-11T23:23:55.311Z"}

**Comment by gdowens** [comment]
May have been an issue related to #66 closing, reopen if can detail more information.
