### ISSUE TITLE
Can create custom commands in vimrc file for vim mode?

### ISSUE THREAD

**Issue by ober01** [decosoftware/deco-ide#173]

**Comment by dabbott** [comment]
Probably not. We're using CodeMirror as a text editor, which has VIM keybindings to emulate the most common features, but doesn't actually run VIM. So it doesn't really handle a lot of the complexity of VIM.

If there's something specific missing from the VIM mode, maybe we can add it.

If somebody *really* dedicated wanted full VIM support, they could try embedding hyperterm into Deco and just using the terminal directly. Another sort of esoteric approach is to use the VIM source compiled into JS: http://coolwanglu.github.io/vim.js/emterpreter/vim.html, but this is probably more work and less usable.

**Comment by ober01** [comment]
thanks
