### ISSUE TITLE
Integrating with existing projects

### ISSUE THREAD

**Issue by elie222** [decosoftware/deco-ide#18]
Is Deco supposed to work out the box with existing projects or do some changes have to be made first like adding a `<View>` wrapper container?

**Comment by dchen** [comment]
You shouldn't have to add a wrapper container like that. Many React Native projects will run without any modification, so please give it a shot. If it doesn't run, please share how you have your project set up (directory structure, etc.) and any error messages, and we'll help you out.

You can try running the simulator from shell, i.e. react-native run-ios, and use Deco for editing the code.

**Comment by gdowens** [comment]
Please see #24
