### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by AmitMY** [decosoftware/deco-ide#188]
I was just wondering if Deco is capable of typescript compiling, structure, and code hinting?
This is crucial in these days, where everyone has many typescript modules.

If not, is there a suggested way to compile TS files on Deco, or should I use an outside watcher to compile everything, so Ill see duplicated files (.ts, .js)

Thanks

**Comment by dabbott** [comment]
I'm not that familiar with the Typescript ecosystem. We considered using the Typescript language services for autocompletion, but went with Flow for the time being. Typescript isn't a priority for us yet.

Probably your best bet is using an outside watcher.
