### ISSUE TITLE
IDE Code Fontsize

### ISSUE THREAD

**Issue by yun0628** [decosoftware/deco-ide#260]
The code fontSize  is  small for me   i want to change it  but i don't get any help from website and other places how to do it

**Comment by smasonvan** [comment]
I agree. Would also like to be able to change the color scheme

**Comment by dabbott** [comment]
Font size and theming settings are available in master or our beta build (available from our homepage). We'll likely push a non-beta release next week with these features.

**Comment by smasonvan** [comment]
excellent.  Thanks for your fast reply.

Really appreciate what you are building here.

cheers
Steve
