### ISSUE TITLE
Deco installs old version of watchman 4.5.0 n OSX

### ISSUE THREAD

**Issue by gmp26** [decosoftware/deco-ide#267]
Deco installed watchman 4.5.0 for me, but OSX has some issues with it which are corrected in version 4.7.0. However installing latest homebrew watchman leads to mismatch between front end and watchman server:
```
$ watchman version
{
    "version": "4.5.0"
}
$ watchman --version
4.7.0
$ ps aux | grep watchman
.../usr/local/Deco/watchman/watchman...
```

How to uninstall cleanly? since Deco appears to have installed the server as a startup process?

**Comment by dchen** [comment]
You can close Deco IDE and just kill any remaining watchman process that is running from /usr/local/Deco. We only install to /usr/local/Deco so it won't overwrite any other installations, so it's safe to kill it and run another version of watchman.
