### ISSUE TITLE
Choice of embedded editor ?

### ISSUE THREAD

**Issue by ianjohnspain** [decosoftware/deco-ide#27]
Hi,

Would be nice to be able to choose the embedded editor or at least right click on a file and OPEN IN for example

What is the embedded editor ? Is it ATOM ? Can we add additional plugins ?

But great what I see so far!

**Comment by dabbott** [comment]
Thanks!

Our Embedded editor is CodeMirror.

Still figuring out how to do a good plugin system.

Not sure about "Open in" but maybe a good place to start would be "Show in Finder" and then you can open in whatever you want from there. I opened a separate issue: https://github.com/decosoftware/deco-ide/issues/34
