### ISSUE TITLE
IDE deletes my file

### ISSUE THREAD

**Issue by hyochan35** [decosoftware/deco-ide#270]
There are few bugs in IDE when I used it for an hour.

I like it's interface and hope it's all solved.

First, when I create folder in IDE sometimes it won't create but when I go to the directory
the folder exists. I have to restart to see the folder.

Second, I moved my js file and renamed it to Capital letter. After that, it deletes my file that I renamed with the original one.

These all happened in recent version.

When I found these two bugs that wouldn't happen in any other IDEs,
I feel somewhat afraid of using it.

**Comment by dchen** [comment]
This is a known issue and will be corrected in an upcoming release. Sorry for the inconvenience! Deco IDE is still pretty new and we recommend backing up your project regularly, using version control or something else.
