### ISSUE TITLE
After I install, it become undefined in Launchpad

### ISSUE THREAD

**Issue by amazingandyyy** [decosoftware/deco-ide#28]
After I install, it become undefined in Launchpad
![screen shot 2016-05-26 at 00 00 52](https://cloud.githubusercontent.com/assets/7886068/15566313/0c178e8c-22d5-11e6-9c93-facb4def18b5.png)

**Comment by gdowens** [comment]
very strange, can you try uninstalling and reinstalling?

**Comment by amazingandyyy** [comment]
hm.. It works really well after reinstalling. Thanks.
