### ISSUE TITLE
Is this project abandoned? 

### ISSUE THREAD

**Issue by Kiura** [decosoftware/deco-ide#282]
disclaimer: I don't do react-native myself

Hello, great project! and having components integrated and being able to use that easily is a deal breaker, for other IDEs for building mobile apps do it. And the look of an app should be done in WYSIWYG (although you have to edit parameters, not the UI itself). 

It seems like the IDE has not been updated for a long time... Is the project still maintained? and if so what are the plans on roadmap, what should we expect soon? 

and one more question:
It is not clear how to install, where to search components that are compatible and why all react-native components are supported (correct me if I am mistaking)

**Comment by jel111** [comment]
I was wondering the same thing myself. Great idea but not enough buzz I guess plus with Fiber who knows

**Comment by Kiura** [comment]
Indeed! With enough commitment, this product could become the only IDE for react-native apps and owners could even monetize it.

**Comment by dchen** [comment]
The project is still active, though we haven't made any new releases or published the code we have been working on recently. We should have more news soon about the product roadmap soon (next few weeks). Thank you for your patience.

**Comment by davidgustys** [comment]
Any updates?

**Comment by nonameolsson** [comment]
@dchen I really would love to see this project being developed. You have done a great work to get it so far! I get that maybe isn't possible for you to work so hard on this as before. But it would be really nice to know what the plans are. Is there a roadmap for this somewhere?

Keep up the good work, I'm looking forward to the day when I can leave my current editor for DECO. Or maybe have Deco as an extension to VS Code or Atom :)

**Comment by JulioOrellana** [comment]
Yes, totally dead 🥺
