### ISSUE TITLE
You Deco guys are fucking retarded !!!

### ISSUE THREAD

**Issue by J-S-Thomas** [decosoftware/deco-ide#293]
Why would you not have a Linux version ready yet. That's fucking stupid and a waste of time for people who post steps to get the thing working on Linux cause the shit don't work on Linux. It's a dope ide but it's been way to long for you not to have a Linux version ready yet.

**Comment by jel111** [comment]
They have moved on

**Comment by HZSamir** [comment]
@jel111 Care to elaborate please?

**Comment by jel111** [comment]
I just say that because there have been pleas on this thread for a long time which have gone unresponsive.

**Comment by dchen** [comment]
Sorry, it's a free and open source project, and we don't have the resources to commit to build a Linux version. The most likely way for a Linux version to become available is if someone in the community is interested in contributing.

**Comment by J-S-Thomas** [comment]
It's almost like the mac people pay you to do this purposely just to get
people to come over to the mac side (dark side). Sorry for calling you guys
retards but you have a good product that everybody needs access to.

**Comment by jel111** [comment]
It's a good idea but never got past that. You ain't missing much.

**Comment by J-S-Thomas** [comment]
Oohhhhhhh I see now. I'm currently using webstorm but I like that drag and
drop feature deco has.
