### ISSUE TITLE
Install via pkg hangs at 'Verifying...', manual installation throws errors for installing json 1.8.1

### ISSUE THREAD

**Issue by steezeburger** [decosoftware/deco-ide#3]
I can't install via the downloaded pkg, and when I try to manually install, I get errors that json 1.8.1 was not installed properly when running `bundle install` and found this as a fix http://stackoverflow.com/questions/29578142/how-to-install-json-gem-failed-to-build-gem-native-extensionmac-10-10

which I'd rather not do. I can install json 1.8.2 gem just fine by the way.

**Comment by gdowens** [comment]
@steezeburger you may be able to give us some clues about the .pkg installation trouble by looking into your System Logs.

**Comment by steezeburger** [comment]
This is logged immediately after trying to install via the pkg. I researched the 60005 error but couldn't find any solutions. Something to do with Mac's Gatekeeper I think?

```
May 25 13:21:13 pocketsand-jr loginwindow[96]: -[SFLListManager(ServiceReplyProtocol) notifyChanges:toListWithIdentifier:] Notified of item changes to list with identifier com.apple.LSSharedFileList.RecentApplications
May 25 13:21:13 pocketsand-jr CoreServicesUIAgent[48116]: Error -60005 creating authorization
```

**Comment by nhtera** [comment]
I have the same issue. I've tried my mac and using [Deco.pkg] install success.
You should also try your Mac.

**Comment by steezeburger** [comment]
That's always a last resort because of everything I have running, but I'll give it a shot!

**Comment by steezeburger** [comment]
That did it. No idea what was going on.
