### ISSUE TITLE
Cyrillic texts changes to "squares"

### ISSUE THREAD

**Issue by alexHlebnikov** [decosoftware/deco-ide#31]
Hi! 

While installing the IDE I've face the following problems: cyrillic text in Mac OS Finder or in menus transformed into "brackets": http://imgur.com/uhbkQp4. My system language is Russian so all the Russian texts in Finder and in system menus became unreadable.

Also all files names on SSD renamed into strange names - for example, *Screenshot 2016-05-26 18.10.12* is looks like "*s2 1 211 12g*". But when I try to rename the files it's show it's real name, not the "*s2 1 211 12g*". 

Can you help me with this problems?

**Comment by dabbott** [comment]
Hmmm... this sounds pretty bad.

@gdowens is there anything we could be doing in the install scripts that would mess with the system language or something?

**Comment by gdowens** [comment]
Yeah, this is insane.

Trying to reproduce now... it's possible the installer changes permissions on some directory that affects your encoding for Cyrillic characters. Just running Deco from source, I can see the Cyrillic fine.

@alexHlebnikov if you manage to fix the problem would appreciate any information.

**Comment by gdowens** [comment]
Just did an install on El Capitan with system language set to Russian. No problems :\ so I'm not sure what happened.

**Comment by alexHlebnikov** [comment]
I've just fixed the problem - there was an update for El Capitan - 10.11.5, after installing and reloading everything went well. 

I can assume what IDE instalation was not the cause of my problem. 
But this happened just in procces of instalation (by the way, Deco was't installed well - installer stuck on last step). So that's why I created this issue.

**Comment by dabbott** [comment]
@alexHlebnikov I'm going to close this. If you're still having trouble with installation, can you create a new issue or reach out to us in slack?

**Comment by alexHlebnikov** [comment]
Ok.
