### ISSUE TITLE
Add mode to disable watchman so that Deco can be used in editor only mode

### ISSUE THREAD

**Issue by dchen** [decosoftware/deco-ide#39]
As a workaround for people who need to run their project outside of Deco, we suggest using Deco as editor only. But in the current version, it aggressively starts watchman which can conflict with running watchman externally.

Can we have a mode to disable watchman / use external watchman? @gdowens

**Comment by dchen** [comment]
Opened this because shivamkumar in Slack is having trouble running project externally.

**Comment by gdowens** [comment]
configure.deco.js feature in 0.7.0 allows users to now forcefully disable Deco packager.
