### ISSUE TITLE
What is the role of the Deco binary? 

### ISSUE THREAD

**Issue by namuol** [decosoftware/deco-ide#4]
What's the role of the [`Deco` binary](https://github.com/decosoftware/deco-ide/blob/4474aac5cbf491663a0ad450568503cb167ed6ac/desktop/deco_unpack_lib/binaries/Deco)? Is the source for it available?

Full disclosure: [I'm attempting to run Deco in Linux](https://twitter.com/louroboros/status/735549212050358272). :neckbeard:

**Comment by gdowens** [comment]
Ah! It is a very poorly named file. This is essentially a cocoascripted cocoa app that is used to run scripts with sudo access. See `desktop/handlers/upgradeHandler.js`

**Comment by gdowens** [comment]
Would be awesome if you get it working. I have looked at https://www.npmjs.com/package/electron-sudo before, might be the right way to go for running the postinstall again after an upgrade.

**Comment by namuol** [comment]
Hmm. Seems like we'd be better off avoiding the need for `sudo` in the first place, if possible.

I'm guessing this is mainly a requirement in OS X when modifying signed/system executables or something to that effect, yes?

**Comment by BHSPitMonkey** [comment]
I was just working toward the same goal and hit the same roadblock. Hope one of us gets somewhere!

**Comment by gdowens** [comment]
@namuol we install some things into the system path (watchman, node, etc) — those generally require sudo. You never know if someone has certain folder permissions set strangely as well, so it avoids the installer failing in those edge cases. Open to finding ways around sudo; I agree it is an annoyance.

**Comment by namuol** [comment]
There could be a path to install deco with `npm`, which would effectively require node to be installed in the first place. Other binaries (i.e. watchman) could just be dependencies in `package.json`, and would be executed with npm scripts.

It's probably safe to assume most React developers have node installed. :)

**Comment by gdowens** [comment]
@namuol 

True, however, we have seen interest from designers and some other non-dev types. 

Perhaps we could include in the installer an optional "Environment Setup" step? Since Developers like to have more transparency into their environment and everyone else doesn't really want to deal with that stuff.

**Comment by namuol** [comment]
Hmm. Taking a step back: Why do watchman and node need to be system executables in the first place? Couldn't they just be bundled with Deco and run from its own installation location? i.e. `./<Deco>/libs/binaries/node`

**Comment by gdowens** [comment]
Yeah, it's worth revisiting the install process entirely. Moving the discussion here #16
