### ISSUE TITLE
Specify npm registry

### ISSUE THREAD

**Issue by ele828** [decosoftware/deco-ide#42]
Maybe we could specify npm registry to speed up installation process?
This one is really fast with CDN support in China, while npm is a little bit slow. We get accustomed to using it.
https://cnpmjs.org/

Thanks.

**Comment by dabbott** [comment]
Is it the initial Deco app installation process that's slow? Or downloading components that have npm dependencies? 

This seems like a good feature. I don't know too much about adding registries, but I'm guessing it would be pretty easy. Maybe a screen in settings. Would you be interested in trying?

**Comment by ele828** [comment]
What I mean is the component downloading process, especially large size component.

Yep, I'm working on it now.
