### ISSUE TITLE
unable to resolve module when using other node modules in github

### ISSUE THREAD

**Issue by wx-chevalier** [decosoftware/deco-ide#44]
i download the snowflake and use npm install & rnpm link , but error occurs when run:
![Uploading ED87EC11-7D8B-4183-A4B2-46281C5AFB85.png…](http://7xkt0f.com1.z0.glb.clouddn.com/ED87EC11-7D8B-4183-A4B2-46281C5AFB85.png)

**Comment by gdowens** [comment]
This error generally happens when A. There is a problem with the npm module installed or B. you are importing the module incorrectly.

Try following the steps in the red screen and see if that fixes the issue for you.
