### ISSUE TITLE
How to uninstall completely?

### ISSUE THREAD

**Issue by akaralar** [decosoftware/deco-ide#45]
I'm on OS X El Capitan and Deco had installed via an installer so I'm not sure if just deleting `Deco.app` will suffice. What do I need to remove in order to uninstall completely? Is there any uninstaller I'm missing?

**Comment by gdowens** [comment]
We do not have an uninstaller, that would be good to add. Deleting the .app file should be enough, but if you really want to wipe all the other stuff you can see what we install in this script https://github.com/decosoftware/deco-ide/blob/master/desktop/Scripts/postinstall

Just `rm -rf` those files/folders

**Comment by gdowens** [comment]
To make it easier, here's the other stuff that's installed outside of the .app
`/usr/local/Deco`
`~/Library/Application Support/com.decosoftware.Deco`
`/usr/local/var/run/watchman`
`~/.Deco`

**Comment by GJNilsen** [comment]
You should put this in the FAQ on the webpage as well.

**Comment by dabbott** [comment]
Or maybe add a script and mention it somewhere

**Comment by GJNilsen** [comment]
#65 does the trick
