### ISSUE TITLE
deco-ide Aurelia??

### ISSUE THREAD

**Issue by adriatic** [decosoftware/deco-ide#46]
I have not (yet) tried deco-ide, so I am writing this based only on a really appealing website and cool looking product. That is sufficient to ask whether you would be interested in working with us (Aurelia-UI-Toolkits and Aurelia-Tools) on creating the Aurelia IDE?

We are internally discussing Aurelia IDE for the longest time, using the identical approach you took and given the fact that you support the open source model, a well made Aurelia IDE could only help your efforts (unless there are some aspects of your business plan that I am not aware of :0-)

**Comment by dabbott** [comment]
@adriatic, we'd definitely be interested! Can you email me and David with a little more info about what you guys do, what you have in mind for Aurelia IDE, and how you were thinking we could collaborate? I don't know too much about your guys' products, but briefly looking at website, it seems like it could be a great fit :)

dabbott@decosoftware.com
dchen@decosoftware.com
