### ISSUE TITLE
Can't run postinstall as root?

### ISSUE THREAD

**Issue by schneidmaster** [decosoftware/deco-ide#6]
Is there a reason why [Scripts/postinstall](https://github.com/decosoftware/deco-ide/blob/master/desktop/Scripts/postinstall#L5-L8) isn't allowed to be run as root?

I'm trying to create a homebrew-cask for Deco and installation is failing because homebrew-cask uses `/usr/sbin/installer`, which in turn must be run as root.

**Comment by gdowens** [comment]
@schneidmaster it's a safeguard to prevent the script from setting ownership of all the files to root. If the application later tries to use some of these files, it will be accessing them as $USER and will throw an exception due to permissions error.

**Comment by schneidmaster** [comment]
Ah okay. The cask will just have to include a manual install step then, thanks for the info.
