### ISSUE TITLE
after using pod ,presss the simulator button,the simulator can't launch

### ISSUE THREAD

**Issue by benzhipeng** [decosoftware/deco-ide#63]
![75c3ef2a-5762-49cb-b1d7-51e3f24529e0](https://cloud.githubusercontent.com/assets/8006405/15696893/75b0b776-27e7-11e6-87be-7eeef2f9137d.png)

**Comment by dchen** [comment]
Is there anything interesting in the Packager Output when you click the simulator button? If you manually launch the project from Xcode, does it work?

**Comment by gdowens** [comment]
@benzhipeng Did you rebuild the .app after adding the pods? If so, where is the target .app file? As of right now Deco hard-coded looks for the path `$ROOT/ios/build/Build/Products/Debug-iphonesimulator/[project_name].app

Can check `~/Library/Application Support/com.decosoftware.Deco/logs.out` for more information and report back.

**Comment by gdowens** [comment]
Better building mechanism has been included in 0.7.0
