### ISSUE TITLE
Deco becomes corrupt when Project is named the same as parent dir

### ISSUE THREAD

**Issue by ashh640** [decosoftware/deco-ide#66]
If I have a folder on my desktop called 'Test' and within it i create my project called 'Test' once I select a file the project tree view simply breaks. See attached image

<img width="266" alt="screen shot 2016-06-01 at 22 57 54" src="https://cloud.githubusercontent.com/assets/10521775/15727088/599ffbcc-284c-11e6-87ff-49fbcbda8530.png">

**Comment by dabbott** [comment]
Interesting... I can reproduce.

Seems to happen when the Project name is the same as the name of the containing dir. It basically breaks the entire Deco UI.

I haven't looked into what's going on. Probably something stupid :P

**Comment by gdowens** [comment]
Seems like something we should fix in the next release.
