### ISSUE TITLE
Why the installation requires admin rights?

### ISSUE THREAD

**Issue by ifraixedes** [decosoftware/deco-ide#67]
I'd like to know why the installation requires admin rights and if it's possible to remove the requirement.

Thanks.

**Comment by gdowens** [comment]
It's basically to guarantee that we can create, add to, and update ownership/permissions for all things outside of the Deco.app. You can see what is happening here: https://github.com/decosoftware/deco-ide/blob/master/desktop/Scripts/postinstall
