### ISSUE TITLE
Update default RN project version

### ISSUE THREAD

**Issue by dabbott** [decosoftware/deco-ide#72]
A lot has changed, we should update.

@dsibiski did you ever give this a shot? (if not, it's cool - we can do it)

Might be worth noting down the steps involved so we can script it.

**Comment by dsibiski** [comment]
I haven't had the chance yet, might be able to try it today. Would you be able to jot down some of those tips you had given me in the chat the other day?

**Comment by dabbott** [comment]
Steps:
- Update the pre-packaged node_modules in `modules.tar.gz` https://github.com/decosoftware/deco-ide/blob/master/desktop/deco_unpack_lib/modules.tar.gz
- Update the default project template: https://github.com/decosoftware/deco-ide/tree/master/desktop/deco_unpack_lib/Project
- Build the default project for iOS: https://github.com/decosoftware/deco-ide/tree/master/desktop/deco_unpack_lib/Project/ios/build/Build/Products/Debug-iphonesimulator/Project.app

Per @gdowens 

> There’ll probably be some some small incompatibilities with launching packager & simulator… you’ll definitely want to test. Update the react native version in the `deco_unpack_lib/Project/package.json` too… as you test these things, make sure you run `npm run copy-libs` — it will basically run the installer script from your src directory.

@dsibiski I'm not sure if it's like a quick thing or if there will be a bunch of unforeseen difficulties, so no pressure. Was just curious if you had tried it yet.

**Comment by dsibiski** [comment]
@dabbott Gotcha, yeah I didn't think it would be quick an easy...but as you mentioned above, go through it and document the process + record challenges...so that perhaps we can automate it or at least make it easier to do in the future.

Thanks for the info!
