### ISSUE TITLE
Cmd + w to close tab

### ISSUE THREAD

**Issue by dabbott** [decosoftware/deco-ide#78]
Currently Cmd + w closes the window. It should close the current tab.

**Comment by noerK** [comment]
I just started with this :)
for now i changed the close window/project and new project hotkeys to "cmd/ctrl + shift + n/w".

**Comment by dabbott** [comment]
@noerK looks like you and timotius collided on this one... maybe we should still merge in your other hotkey changes?

**Comment by noerK** [comment]
No Problem :)

I'll just pull the current state and redo my changes.

**Comment by gdowens** [comment]
merged and in 0.7.0
