### ISSUE TITLE
Adjustable text editor font size

### ISSUE THREAD

**Issue by dabbott** [decosoftware/deco-ide#79]
Font size should be adjustable.

Probably I need to do some editor refactoring before attempting this. Right now it would be tricky - but after a refactor it would be trivial.

**Comment by mattgabor** [comment]
+1

**Comment by yagamis** [comment]
+1, yes, the font of UI is too small to see...  horrible!!!

**Comment by conradwt** [comment]
@dabbott Has this functionality made it to the Deco Roadmap?

**Comment by dabbott** [comment]
Done! https://github.com/decosoftware/deco-ide/pull/163

![editor themes and font size](https://cloud.githubusercontent.com/assets/1198882/18415135/f5cd4268-779b-11e6-9ef6-a7006f6bb14f.gif)

**Comment by davin12x** [comment]
I don't have font size option in Deco?

**Comment by dabbott** [comment]
It's not on our public build yet. Only in master/dev branches.

**Comment by muescha** [comment]
i miss this too - it is to small to read the code :(

please also:
- select font
- adjust font size with `cmd+'+'` and `cmd+'-'` and reset to default font with `cmd+'0'`

**Comment by xuechinahb** [comment]
font is too small. Waiting the new version......

**Comment by pikitgb** [comment]
Is this new version ready ? I love this IDE

**Comment by benxuhuang** [comment]
Please release this features, many people using high resolution displays now, The font is too small really. Thanks!

**Comment by jcrain** [comment]
Deco is awesome! And it will be super awesome when I can increase the font size!

**Comment by einfalles** [comment]
Since they got sucked into AirBnb option has been taken away

**Comment by saintfirewater** [comment]
Is changing font size applied?
