### ISSUE TITLE
Extremely low IDE download speed

### ISSUE THREAD

**Issue by SergeyKuzmich** [decosoftware/deco-ide#86]
Downloading IDE from official website is extremely slow and useless (East Europe Region), because download speed is about ~40KB/s on 100Mb/s connection.

Maybe you need to upload distibutive to github as release or provide more accesible storage?

**Comment by dabbott** [comment]
Yes, we're gonna do this. As part of our next release (should be next week...) you'll be able to get the binaries as github releases.

**Comment by SergeyKuzmich** [comment]
Thank you for this and for IDE!
