### ISSUE TITLE
"Chat With Deco Team" link Closes Deco

### ISSUE THREAD

**Issue by 3DEsprit** [decosoftware/deco-ide#93]
OS: OSX 10.11.5
Deco: 1.1.2 (0.6.0)

Clicking the Help > Chat with Deco Team... link closes the client shortly after clicking it. This happens any time the link is clicked, even with newly created projects, empty projects, and even shortly after opening Deco. There is plenty of memory free for this operation, and no other obvious reasons for this to happen; if this is not intended. I selectively chose not to say "crash" as this does not show any oddities in the console.

I'm sorry for the lack of information. I have yet to find a way to receive any more output from Deco. Anytime I try to start Deco from a terminal (i.e. open -a  /Applications/Deco.app), it refuses to start, and without any output to give any idea why. I'm not sure if this is by design, but if it's not I'll be happy to fill out another issue report. 

If it is by design, is there a better way to receive debug output for issues?

**Comment by gdowens** [comment]
@3DEsprit you can find logs at ~/Library/Application Support/com.decosoftware.Deco/logs.out — this bug has already been patched, and we are working to get a release out asap. 

Thanks!

**Comment by 3DEsprit** [comment]
Oh great to know! Thanks!
